// lib/generator/emitter.ts
import type { TestSuite, TestCase, TestStep, Assertion } from '@/lib/schemas/test-spec';

export interface EmittedFile {
  filename: string;
  content: string;
}

/**
 * Converts a validated TestSuite into .spec.ts + playwright.config.ts.
 * Pure function — no I/O, no DB access.
 */
export function emitTestFiles(spec: TestSuite): EmittedFile[] {
  return [
    { filename: `${toSlug(spec.suiteName)}.spec.ts`, content: emitSuiteFile(spec) },
    { filename: 'playwright.config.ts', content: emitConfig(spec.baseUrl) },
  ];
}

// ─── Suite ────────────────────────────────────────────────────────────────────

function emitSuiteFile(spec: TestSuite): string {
  // Group test cases by their group field → nested describe blocks
  const groups = new Map<string, TestCase[]>();
  for (const tc of spec.testCases) {
    const bucket = groups.get(tc.group) ?? [];
    bucket.push(tc);
    groups.set(tc.group, bucket);
  }

  const lines: string[] = [
    `// Generated by TestPilot — https://testpilot-swart.vercel.app`,
    `// Target: ${spec.targetUrl}`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
    `import { test, expect } from '@playwright/test';`,
    ``,
    `test.describe('${esc(spec.suiteName)}', () => {`,
  ];

  if (spec.notes?.length) {
    lines.push(`  /**`);
    for (const note of spec.notes) lines.push(`   * ${note}`);
    lines.push(`   */`);
  }

  for (const [groupName, cases] of groups) {
    lines.push('');
    lines.push(`  test.describe('${esc(groupName)}', () => {`);
    for (const tc of cases) {
      lines.push('');
      for (const l of emitTestCase(tc)) lines.push(`    ${l}`);
    }
    lines.push(`  });`);
  }

  lines.push('');
  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

// ─── Test case ────────────────────────────────────────────────────────────────

function emitTestCase(tc: TestCase): string[] {
  const lines: string[] = [];
  const fn = tc.skip ? 'test.skip' : 'test';
  const tags = tc.tags?.length ? `  // [${tc.tags.join(', ')}]` : '';

  if (tc.skip && tc.skipReason) {
    lines.push(`// Skip reason: ${tc.skipReason}`);
  }

  lines.push(`${fn}('${esc(tc.title)}', async ({ page }) => {${tags}`);

  for (const step of tc.steps) {
    for (const l of emitStep(step)) lines.push(`  ${l}`);
  }

  lines.push(`});`);
  return lines;
}

// ─── Step ─────────────────────────────────────────────────────────────────────

function emitStep(step: TestStep): string[] {
  const lines: string[] = [];
  lines.push(`// ${step.description}`);

  const actionLine = emitAction(step);

  if (step.optional) {
    // Wrap optional steps in try/catch — element may not be present
    lines.push(`try {`);
    lines.push(`  ${actionLine}`);
    if (step.assertion) lines.push(`  ${emitAssertion(step.assertion, step.locator)}`);
    lines.push(`} catch { /* optional — element may not be present */ }`);
  } else {
    lines.push(actionLine);
    if (step.assertion) lines.push(emitAssertion(step.assertion, step.locator));
  }

  return lines;
}

// ─── Action emitter ───────────────────────────────────────────────────────────

function emitAction(step: TestStep): string {
  const { action, locator, value } = step;
  // L() produces a Locator expression; placeholder keeps emitted code valid TS
  const L = locator
    ? `page.locator('${locator}')`
    : `page.locator('/* TODO: locator missing */')`;

  switch (action) {
    case 'navigate':
      return `await page.goto('${value ?? ''}');`;
    case 'click':
      return `await ${L}.click();`;
    case 'dblClick':
      return `await ${L}.dblclick();`;
    case 'rightClick':
      return `await ${L}.click({ button: 'right' });`;
    case 'fill':
      return `await ${L}.fill('${esc(value ?? '')}');`;
    case 'clear':
      return `await ${L}.clear();`;
    case 'select':
      return `await ${L}.selectOption('${esc(value ?? '')}');`;
    case 'check':
      return `await ${L}.check();`;
    case 'uncheck':
      return `await ${L}.uncheck();`;
    case 'hover':
      return `await ${L}.hover();`;
    case 'focus':
      return `await ${L}.focus();`;
    case 'blur':
      return `await ${L}.blur();`;
    case 'press':
      return `await ${L}.press('${esc(value ?? '')}');`;
    case 'upload':
      return `await ${L}.setInputFiles('${esc(value ?? '')}');`;
    case 'scroll':
      if (value === 'top') return `await page.evaluate(() => window.scrollTo(0, 0));`;
      if (value === 'bottom') return `await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));`;
      return locator ? `await ${L}.scrollIntoViewIfNeeded();` : `await page.evaluate(() => window.scrollTo(0, 0));`;
    case 'drag':
      // value holds the target locator to drag to
      return `await ${L}.dragTo(page.locator('${esc(value ?? '')}'));`;
    case 'waitForSelector':
      return `await page.waitForSelector('${locator ?? value ?? ''}');`;
    case 'waitForURL':
      return `await page.waitForURL('${esc(value ?? '')}');`;
    case 'waitForResponse':
      return `await page.waitForResponse('${esc(value ?? '')}');`;
    case 'waitForTimeout':
      return `await page.waitForTimeout(${Number(value ?? 1000)});`;
    case 'screenshot':
      return `await page.screenshot({ path: 'screenshots/${esc(value ?? 'screenshot')}.png' });`;
    default:
      return `// [unhandled action: ${action}]`;
  }
}

// ─── Assertion emitter ────────────────────────────────────────────────────────

function emitAssertion(assertion: Assertion, stepLocator?: string): string {
  // assertion.locator overrides step locator; fall back to page for URL/title
  const locatorExpr = assertion.locator ?? stepLocator;
  const not = assertion.not ? '.not' : '';
  const { expected, expectedCount, attribute } = assertion;

  // Page-scoped assertions — always use `page` regardless of locator
  if (assertion.type === 'toHaveURL') {
    return `await expect(page)${not}.toHaveURL('${esc(expected ?? '')}');`;
  }
  if (assertion.type === 'toHaveTitle') {
    return `await expect(page)${not}.toHaveTitle('${esc(expected ?? '')}');`;
  }

  const target = locatorExpr ? `page.locator('${locatorExpr}')` : 'page';

  switch (assertion.type) {
    case 'toBeVisible':
      return `await expect(${target})${not}.toBeVisible();`;
    case 'toBeHidden':
      return `await expect(${target})${not}.toBeHidden();`;
    case 'toBeEnabled':
      return `await expect(${target})${not}.toBeEnabled();`;
    case 'toBeDisabled':
      return `await expect(${target})${not}.toBeDisabled();`;
    case 'toBeChecked':
      return `await expect(${target})${not}.toBeChecked();`;
    case 'toBeEmpty':
      return `await expect(${target})${not}.toBeEmpty();`;
    case 'toHaveText':
      return `await expect(${target})${not}.toHaveText('${esc(expected ?? '')}');`;
    case 'toContainText':
      return `await expect(${target})${not}.toContainText('${esc(expected ?? '')}');`;
    case 'toHaveValue':
      return `await expect(${target})${not}.toHaveValue('${esc(expected ?? '')}');`;
    case 'toHaveAttribute':
      return `await expect(${target})${not}.toHaveAttribute('${esc(attribute ?? '')}', '${esc(expected ?? '')}');`;
    case 'toHaveClass':
      return `await expect(${target})${not}.toHaveClass('${esc(expected ?? '')}');`;
    case 'toHaveCSS':
      return `await expect(${target})${not}.toHaveCSS('${esc(attribute ?? '')}', '${esc(expected ?? '')}');`;
    case 'toHaveCount':
      return `await expect(${target})${not}.toHaveCount(${expectedCount ?? 0});`;
    case 'toMatchSnapshot':
      return `await expect(${target})${not}.toMatchSnapshot();`;
    default:
      return `// [unhandled assertion: ${assertion.type}]`;
  }
}

// ─── Config emitter ───────────────────────────────────────────────────────────

function emitConfig(baseUrl: string): string {
  return `// playwright.config.ts — generated by TestPilot
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  use: {
    baseURL: '${baseUrl}',
    headless: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  reporter: [['html', { open: 'never' }]],
});
`;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function toSlug(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'test-suite'
  );
}

function esc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}